### ISSUE TITLE
Skia v0.1.230 breaks package

### ISSUE THREAD

**Issue by KrisLau** [enzomanuelmangano/react-native-skia-gesture#10]
[Skia v0.1.230](https://github.com/Shopify/react-native-skia/releases/tag/v0.1.230-beta) removes the Skia Value API (useValue, useComputedValue, runTiming, etc) which breaks the package. The package will probably have to migrate to the methods aligned in the [docs](https://shopify.github.io/react-native-skia/docs/animations/animations/) which utilize Reanimated v3. Probably somewhat related to https://github.com/enzomanuelmangano/react-native-skia-gesture/issues/9

**Comment by enzomanuelmangano** [comment]
Sorry for the delay, added Reanimated and Gesture Handler support: https://github.com/enzomanuelmangano/react-native-skia-gesture/pull/11

**Comment by KrisLau** [comment]
Thank you so much I really appreciate it!

**Comment by KrisLau** [comment]
@enzomanuelmangano For some reason, after the update I seem to be having issues with the onActive gesture. I put a console.log in the onActive event handler and it doesn't seem to begetting hit at all when I click and drag.  I also tried rolling back the updates but for some reason even after rolling back commits to a point where I believed it to be working, it still doesn't work. Not sure where I might've messed up.

I tried running the README example in a snack (https://snack.expo.dev/@kris_lau/witty-red-edamame) and seem to be getting an `Cannot read property 'createValue' of undefined` error.

**Comment by enzomanuelmangano** [comment]
> @enzomanuelmangano For some reason, after the update I seem to be having issues with the onActive gesture. I put a console.log in the onActive event handler and it doesn't seem to begetting hit at all when I click and drag. I also tried rolling back the updates but for some reason even after rolling back commits to a point where I believed it to be working, it still doesn't work. Not sure where I might've messed up.
> 
> I tried running the README example in a snack (https://snack.expo.dev/@kris_lau/witty-red-edamame) and seem to be getting an `Cannot read property 'createValue' of undefined` error.

I was able to reproduce the issue by updating Reanimated & Skia. [This PR](https://github.com/enzomanuelmangano/react-native-skia-gesture/pull/12) solves the problems. Feel free to update to v0.3.5 to check the changes. 
Unfortunately a lot of things changed between the updates and because of that, I'm not supporting the internal context anymore. That's not a huge deal since you can handle the context outside as a shared value. 

### Old

```tsx 
  const cx = useSharedValue(100);
  const cy = useSharedValue(100);

  const circleGesture = useGestureHandler<{ x: number; y: number }>({
    onStart: (_, context) => {
      'worklet'; // Remember the 'worklet' keyword
      context.x = cx.value;
      context.y = cy.value;
    },
    onActive: ({ translationX, translationY }, context) => {
      'worklet';
      cx.value = context.x + translationX;
      cy.value = context.y + translationY;
    },
  });

```


### New 
```tsx
  const cx = useSharedValue(100);
  const cy = useSharedValue(100);

  const context = useSharedValue({ x: 0, y: 0 });

  const circleGesture = useGestureHandler({
    onStart: () => {
      'worklet'; // Remember the 'worklet' keyword
      context.value = {
        x: cx.value,
        y: cy.value,
      }
    },
    onActive: ({ translationX, translationY }, context) => {
      'worklet';
      cx.value = context.value.x + translationX;
      cy.value = context.value.y + translationY;
    },
  });
  ```
