### ISSUE TITLE
Reanimted V3 support

### ISSUE THREAD

**Issue by Asad520** [enzomanuelmangano/react-native-skia-gesture#9]
Does this not support reanimated v3 yet? I'm not able to make any component `Touchable`. I'm using Reanimated v3.6.0-nightly-20231114-0837247d4 with Fabric enabled

**Comment by enzomanuelmangano** [comment]
Sorry for the delay, added Reanimated and Gesture Handler support: https://github.com/enzomanuelmangano/react-native-skia-gesture/pull/11
